@url = http://localhost:5000/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZGQ3NjJiOC01YTc2LTQ3YzMtOTNiZC1mYWFkZWEyZDdmMmIiLCJ1bmlxdWVfbmFtZSI6ImNkZDc2MmI4LTVhNzYtNDdjMy05M2JkLWZhYWRlYTJkN2YyYiIsImp0aSI6IjUyNjk2NDg1LWJkMGYtNDA3Zi04ZjcyLWQwMzI0NWZjYTE0MiIsImlhdCI6IjE2MTg0MjE4MTgxMjUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTYxODQyMTgxOCwiZXhwIjoxNjE4NDU3ODE4LCJpc3MiOiJjb25mYWIifQ.16gXbucG8Nql50W8rxFVfYmo9Krpt0pNeE59pE7_cYQ
###
GET {{url}}

###
GET {{url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}",
  "claims": {
    "permissions": ["conferences", "hosts", "speakers", "tickets", "users"]
  }
}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}