@url = http://localhost:5000/conferences-module
@hostId = a07e4d67-988b-48b0-b075-e9bfff04cdec
@conferenceId = c20dfbe1-085a-45d1-97c1-32c4246b1c70
@accessToken = secret

###
GET {{url}}

###
POST {{url}}/hosts
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Host #2",
  "description": "Lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Host #2"
}

###
DELETE {{url}}/hosts/{{hostId}}
Authorization: Bearer {{accessToken}}

###
POST {{url}}/conferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "hostId": "{{hostId}}",
  "name": "Conference #1",
  "description": "Lorem ipsum",
  "location": "Test 123",
  "from": "2021-05-01",
  "to": "2021-05-02",
  "participantsLimit": 100,
  "logoUrl": null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
PUT {{url}}/conferences/{{conferenceId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Conference #2",
  "description": "Lorem ipsum",
  "location": "Test 123",
  "from": "2021-05-01",
  "to": "2021-05-02",
  "participantsLimit": 100,
  "logoUrl": null
}

###
DELETE {{url}}/conferences/{{conferenceId}}
Authorization: Bearer {{accessToken}}